version: "3"

services:
  traefik:
    image: traefik
    container_name: traefik
    ports:
      - "80:80"
      - "8080:8080"
      - "443:443"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
  blog:
    image: wordpress
    container_name: blog
    environment:
      WORDPRESS_DB_PASSWORD:
    labels:
      - traefik.backend=blog
      - traefik.frontend.rule=Host:blog.flowtrax.net
      - traefik.docker.network=web
      - traefik.port=80
    networks:
      - internal
      - web
    depends_on:
      - mysql
  web:
          build: ./flowtrax-web
          container_name: web
          labels:
                  - traefik.backend=web
                  - traefik.frontend.rule=Host:flowtrax.net
                  - traefik.docker.network=web
                  - traefik.port=8080
          networks:
                  - internal
                  - web
          environment:
                  NODE_ENV: production
  weworld:
          build: ./WeWorldServer
          container_name: weworld
          labels:
                  - traefik.backend=weworld
                  - traefik.frontend.rule=Host:weworld.flowtrax.net
                  - traefik.docker.network=web
                  - traefik.port=3000
          networks:
                  - internal
                  - web
          environment:
                  NODE_ENV: production
  mongodb:
          image: mongo
          container_name: mongodb
          volumes:
                  - /data/db:/data/db
          ports:
                  - 27107:27017
          expose:
                  - "27017"
          restart: always
          environment:
                  - MONGO_DATA_DIR=/data/db
                  - MONGO_LOG_DIR=/dev/null
          networks:
                  - web
          labels:
                  - traefik.enable=false    
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD:
    networks:
      - internal
    labels:
      - traefik.enable=false

networks:
  web:
    external: true
  internal:
    external: false
